Replace hyphen with underscore in ahSettingsFile (#86)
acquia/drupal-environment-detector pull request #87
Opened 2024-04-02 21:35 UTC by ssu-carlsoni

Fixes # 
--------
#86 

Motivation
----------
Acquia Cloud does not support hyphens in db names.  FilePaths::ahSettingsFile handles periods but not hyphens.

Proposed changes
---------
Ensure FilePaths::ahSettingsFile return the correct settings file when a site_name contains a hyphen

Alternatives considered
---------
A hyphen is valid character in domain names.

Testing steps
---------
Add a multisite with a hyphen in the name to a project on Acquia Cloud using Acquia Recommended Settings.
example: childrens-school.domain.com

2024-06-25 19:16 UTC, danepowell requested changes
I think this can be simplified. Check my suggestion, make sure tests pass, then I'm happy to merge.

2024-06-25 19:16 UTC, danepowell commented on src/FilePaths.php
> +    $site_name = str_replace('-', '_', $site_name);
```suggestion
    // Acquia Cloud does not support periods or hyphens in db names.
    $site_name = str_replace(['.','-'], '_', $site_name);
```

2024-06-25 23:38 UTC, ssu-carlsoni commented
Thank you @danepowell. I learned str_replace can accept arrays for search and/or replace.

2024-06-26 19:02 UTC, danepowell commented
Thanks. I think there's a CI outage right now but I'll circle back to this tomorrow.

2024-06-27 19:43 UTC, merged